const keys = [
  { code: "Backquote", value: "ё" },
  { code: "KeyQ", value: "й" },
  { code: "KeyW", value: "ц" },
  { code: "KeyE", value: "у" },
  { code: "KeyR", value: "к" },
  { code: "KeyT", value: "е" },
  { code: "KeyY", value: "н" },
  { code: "KeyU", value: "г" },
  { code: "KeyI", value: "ш" },
  { code: "KeyO", value: "щ" },
  { code: "KeyP", value: "з" },
  { code: "BracketLeft", value: "х" },
  { code: "BracketRight", value: "ъ" },
  { code: "KeyA", value: "ф" },
  { code: "KeyS", value: "ы" },
  { code: "KeyD", value: "в" },
  { code: "KeyF", value: "а" },
  { code: "KeyG", value: "п" },
  { code: "KeyH", value: "р" },
  { code: "KeyJ", value: "о" },
  { code: "KeyK", value: "л" },
  { code: "KeyL", value: "д" },
  { code: "Semicolon", value: "ж" },
  { code: "Quote", value: "э" },
  { code: "KeyZ", value: "я" },
  { code: "KeyX", value: "ч" },
  { code: "KeyC", value: "с" },
  { code: "KeyV", value: "м" },
  { code: "KeyB", value: "и" },
  { code: "KeyN", value: "т" },
  { code: "KeyM", value: "ь" },
  { code: "Comma", value: "б" },
  { code: "Period", value: "ю" },
];

export default keys;
